version: '3.8'

services:
  app:
    image: stevendegwa/zentu_app:latest
    container_name: zentu_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zentu_db
      SPRING_DATASOURCE_USERNAME: zentu_user
      SPRING_DATASOURCE_PASSWORD: zentu_pass
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: zentu_user
      POSTGRES_PASSWORD: zentu_pass
      POSTGRES_DB: zentu_db
    ports:
      - "5427:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
