name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  setup-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: zentu_user
          POSTGRES_PASSWORD: zentu_pass
          POSTGRES_DB: zentu_test_db
        options: >-
          --health-cmd="pg_isready -U zentu_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/zentu_test_db
          SPRING_DATASOURCE_USERNAME: zentu_user
          SPRING_DATASOURCE_PASSWORD: zentu_pass

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: zentu-app-jar
          path: target/*.jar

  docker-build-push:
    runs-on: ubuntu-latest
    needs: setup-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: zentu-app-jar
          path: target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-platform docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: stevendegwa/zentu_app:latest
          platforms: linux/amd64,linux/arm64/v8

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Run deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ZENTU_SERVER_IP }}
          username: ${{ secrets.ZENTU_SSH_USER }}
          port: 22
          key: ${{ secrets.ZENTU_PASSWORD_SSH_KEY }}
          script_stop: true
          script: |
            sudo chown -R $USER:$USER /srv/apps/live/zentu-app
            cd /srv/apps/live/zentu-app/
            git config --global --add safe.directory /srv/apps/live/zentu-app
            git pull origin main
            docker-compose pull
            docker-compose up -d --build
  clean:
    name: Clean up Docker Cache
    runs-on: ubuntu-22.04
    needs: deploy

    steps:
      - name: SSH and Prune Docker Resources
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ZENTU_SERVER_IP }}
          username: ${{ secrets.ZENTU_SSH_USER }}
          port: 22
          key: ${{ secrets.ZENTU_PASSWORD_SSH_KEY }}
          script: |
            docker image prune -af
            docker builder prune -af
